# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pyStringChecks',
                'doc_host': 'https://rajmallah.github.io',
                'git_url': 'https://github.com/rajmallah/pyStringChecks',
                'lib_path': 'pyStringChecks'},
  'syms': {'pyStringChecks.core': {'pyStringChecks.core.foo': ('core.html#foo', 'pyStringChecks/core.py')}}}